{
 "title": "OpenShift - CPU Troubleshooter",
 "tags": [ "CPU" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(kube_pod_info, host_ip)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kube_pod_info{host_ip=~\"$server\"}, node)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_cpu_seconds_total,  job)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\", instance=\"$instance\"}[1m])) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Per Core Heat Map - Rate",
   "type": "status-history",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{instance=\"$instance\", mode=\"idle\"}[$__rate_interval])) * 100",
     "legendFormat": "core {{cpu}}"
    }
   ]
  },
  {
   "title": "Processes Waiting for CPU",
   "type": "timeseries",
   "description": "more processes to be run than CPU time available to handle them",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_schedstat_waiting_seconds_total{instance=~\"$instance\"}[$__rate_interval]) ",
     "legendFormat": "Cpu - {{cpu}}"
    }
   ]
  },
  {
   "title": "Top Containers on Node",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod, container)(rate(container_cpu_usage_seconds_total{image!=\"\", instance=\"$server:10250\",container!=\"POD\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "Throttled Seconds",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{instance=\"$server:10250\", container=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Advanced PSI enabled", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } }
 ]
}