{
 "title": "OpenShift - Node Stats",
 "description": "Dashboard to for node information",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(kube_pod_info, host_ip)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kube_pod_info{host_ip=~\"$server\"}, node)"
    }
   },
   {
    "name": "pods",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{node =~\"$instance\"}, pod)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(kube_node_role{node=~\"$instance\"}, role)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])))",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$instance\"})",
     "legendFormat": "1 Minute Avg"
    },
    {
     "expr": "avg(node_load5{instance=~\"$instance\"})",
     "legendFormat": "5 Minute Avg"
    },
    {
     "expr": "avg(node_load15{instance=~\"$instance\"})",
     "legendFormat": "15 Minute Avg"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(irate(node_cpu_seconds_total {mode=\"iowait\", instance=\"$instance\"} [2m])) without (cpu)) / count(node_cpu_seconds_total) without (cpu) * 100",
     "legendFormat": "IOWait"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemFree_bytes{instance=~\"$instance\"} - node_memory_Buffers_bytes{instance=~\"$instance\"} - node_memory_Cached_bytes{instance=~\"$instance\"})",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "avg(node_memory_Buffers_bytes{instance=~\"$instance\"})",
     "legendFormat": "Memory Buffers"
    },
    {
     "expr": "avg(node_memory_Cached_bytes{instance=~\"$instance\"})",
     "legendFormat": "Memory Cached"
    },
    {
     "expr": "avg(node_memory_MemFree_bytes{instance=~\"$instance\"})",
     "legendFormat": "Memory Free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "-/+ buffers/cache",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg((node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemFree_bytes{instance=~\"$instance\"}  - node_memory_Buffers_bytes{instance=~\"$instance\"} - node_memory_Cached_bytes{instance=~\"$instance\"}) / node_memory_MemTotal_bytes{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Written"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=~\"$instance\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",instance=~\"$instance\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "sum (rate(node_network_receive_bytes_total{instance=~\"$instance\",device!~\"lo\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "sum (rate(node_network_transmit_bytes_total{instance=~\"$instance\",device!~\"lo\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pods on Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\", node=~\"$instance\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{node=\"$instance\", container!=\"POD\",container!=\"\", pod!=\"\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}