{
 "title": "Cluster Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Alerts Dashboard", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 } },
  {
   "title": "Compute Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:node_instance_type_count:sum{label_node_role_kubernetes_io!=\"master\"})"
    }
   ]
  },
  {
   "title": "Allocatable Cores",
   "type": "stat",
   "description": "Excludes control plane",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io!=\"master\"})"
    }
   ]
  },
  {
   "title": "Cluster Http Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Req" }
   ],
   "targets": [
    {
     "expr": "code:cluster:ingress_http_request_count:rate5m:sum",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Cluster Operators by Failed Condition",
   "type": "graph",
   "description": "Cluster operators in Progress, Degraded, Failing, etc...",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Conditions" }
   ],
   "targets": [
    {
     "expr": "(cluster_operator_conditions{condition!~\"Available|Upgradeable|RetrievedUpdates\"} == 1)",
     "legendFormat": "{{name}} ({{condition}})"
    }
   ]
  },
  {
   "title": "Application Projects",
   "type": "stat",
   "description": "Excludes infrastructure namespaces",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_labels{namespace!~\"(default|kube|openshift).*\"})"
    }
   ]
  },
  {
   "title": "Allocatable Memory",
   "type": "stat",
   "description": "Excludes control plane",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io!=\"master\"})"
    }
   ]
  },
  {
   "title": "Application Pods",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\",namespace!~\"(default|kube|openshift).*\"})"
    }
   ]
  },
  {
   "title": "Allocated App Storage",
   "type": "stat",
   "description": "Persistent volume claims for applications",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes {namespace!~\"(default|kube|openshift).*\"})/1e+9"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Waiting and Terminated Containers",
   "type": "graph",
   "description": "Containers in cluster by state, excluding Running and Completed pod status",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (kube_pod_container_status_waiting_reason)",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "sum by (reason) (kube_pod_container_status_terminated_reason{reason=~\"ContainerCannotRun|Error|OOMKilled\"})",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Kubelet Operations Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket[5m])) by (operation_type, le))",
     "legendFormat": "runtime: {{operation_type}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_cgroup_manager_duration_seconds_bucket[5m])) by (operation_type, le))",
     "legendFormat": "cgroup: {{operation_type}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pod_worker_duration_seconds_bucket[5m])) by (operation_type, le))",
     "legendFormat": "worker: {{operation_type}}"
    }
   ]
  },
  {
   "title": "Container Runtime Operations Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (operation_type) (rate(container_runtime_crio_operations_latency_microseconds[5m]))",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Alerts by State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (alertname, severity)(ALERTS{alertname!=\"Watchdog\"})",
     "legendFormat": "{{alertname}} ({{severity}})"
    }
   ]
  },
  {
   "title": "APIServer Requests by Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "code:apiserver_request_total:rate:sum",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "APIServer Requests by Verb",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total[5m]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Etcd Server has Leader",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "etcd_server_has_leader", "legendFormat": "{{pod}}" }
   ]
  },
  { "title": "Cluster Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Cluster Pod Requests and Limits",
   "type": "graph",
   "description": "Kubernetes schedules based on CPU and memory pod requests",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (pod) (kube_pod_container_resource_requests{resource=\"cpu\",namespace!~\"(default|kube|openshift).*\"}) and count (kube_pod_status_phase{phase=~\"Running|Pending|Unknown\"} == 1) by (pod)) / sum (machine_cpu_cores)",
     "legendFormat": "cpu.requests"
    },
    {
     "expr": "sum(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace!~\"(default|kube|openshift).*\"}) and count(kube_pod_status_phase{phase=~\"Running|Pending|Unknown\"} == 1) by (pod)) / sum (machine_memory_bytes)",
     "legendFormat": "memory.requests"
    },
    {
     "expr": "sum(sum by (pod) (kube_pod_container_resource_limits{resource=\"cpu\",namespace!~\"(default|kube|openshift).*\"}) and count (kube_pod_status_phase{phase=~\"Running|Pending|Unknown\"} == 1) by (pod)) / sum (machine_cpu_cores)",
     "legendFormat": "cpu.limits"
    },
    {
     "expr": "sum(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace!~\"(default|kube|openshift).*\"}) and count(kube_pod_status_phase{phase=~\"Running|Pending|Unknown\"} == 1) by (pod)) / sum (machine_memory_bytes)",
     "legendFormat": "memory.limits"
    }
   ]
  },
  {
   "title": "Pods per Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubelet_running_pods", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Pods per App Namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (node_namespace_pod:kube_pod_info:{namespace!~\"(openshift).*\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}