{
 "title": "OpenShift - API Server Troubleshooter",
 "description": "Dashboards for obsessive people",
 "tags": [ "kube-apir" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(apiserver_current_inflight_requests, job)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Request Terminations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_terminations_total{job=\"$job\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "API Pod Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"apiserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Secret Cache Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_envelope_encryption_dek_cache_fill_percent{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Resource Watches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, max by (kind)(apiserver_registered_watchers{job=\"$job\"}))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Unavailable Apiservice",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (name)(max_over_time(aggregator_unavailable_apiservice{job=\"$job\"}[$__interval])) > 0.1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Core API  Request Duration Heatmap",
   "type": "heatmap",
   "description": "I recommend using a recording rules via kube stack prometheus, please note Max Data points and interval",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(apiserver_request_duration_seconds_bucket{job=\"$job\",subresource=\"\",verb!=\"WATCH\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Etcd Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (le)(increase(etcd_request_duration_seconds_bucket{job=\"apiserver\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Slowest Requests (P90) - 5min",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3, cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{job=\"$job\",quantile=\"0.9\", subresource=\"\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Total inflight request",
   "type": "timeseries",
   "description": "Request rate by error code",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(max_over_time(apiserver_current_inflight_requests{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% Client Error Rate - 2m",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance,code)(increase(rest_client_requests_total{job=\"$job\", code!~\"2..\", code!~\"<error>\"}[2m])) > 0",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}