{
 "title": "OpenShift - Kubelet Troubleshooter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(kubelet_runtime_operations_total{ job=\"$job\", metrics_path=\"/metrics\"}, instance)"
    }
   },
   {
    "name": "job",
    "label": "kubelet",
    "query": {
     "query": "label_values(kubelet_node_name,  job)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pods{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{node_kubernetes_io_instance_type}}"
    }
   ]
  },
  {
   "title": "Kubelet Inflight Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kubelet_http_inflight_requests{job=\"$job\", instance=\"$instance\", path=\"metrics\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Kubelet Resident Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Kubelet memory"
    }
   ]
  },
  {
   "title": "Kubelet Discard Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(kubelet_pleg_discard_events{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Discard Events"
    }
   ]
  },
  {
   "title": "Pod Worker Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, increase(kubelet_pod_worker_duration_seconds_bucket{instance=\"$instance\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Current Container Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_containers{job=\"$job\", instance=\"$instance\", container_state!=\"exited\"}",
     "legendFormat": "{{container_state}}"
    }
   ]
  },
  {
   "title": "Pleg Relist Duration",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "increase(kubelet_pleg_relist_duration_seconds_bucket{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Run Podsandbox Duration",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "increase(kubelet_run_podsandbox_duration_seconds_bucket{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Runtime Operations Errors",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(kubelet_runtime_operations_errors_total{instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Kubelet Pod Start Duration - Seconds",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "increase(kubelet_pod_start_duration_seconds_bucket{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubelet Http Requests Duration",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "increase(kubelet_http_requests_duration_seconds_bucket{instance=\"$instance\", path=\"metrics\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}